#!/bin/sh

## 
# Cinepass API script to get one movie id by title
#
# Example:
#
#     $ export CINEPASS_API_KEY=123456679
#     $ get-movie-id-by-title "spider-man"
#
# Tracking:
#
#   * Command: cinepass-get-movie-id-by-title.sh
#   * Version: 1.0.0
#   * Created: 2017-08-22
#   * Updated: 2017-08-24
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

title="$1"

curl -sSLG "http://api.cinepass.de/v4/movies" \
  -H "X-Api-Key: $CINEPASS_API_KEY" \
  --data-urlencode "search_field=title" \
  --data-urlencode "search_query=$title" |
  jq -r ".movies[].id" |
  head -1
