#!/bin/sh

## 
# International Showtimes API script to get cinema id by name and location
#
# Syntax:
#
#     internationalshowtimes-get-cinema-id-by-name-and-location <name> [latitude longitude]
#
# Example:
#
#     $ export INTERNATIONALSHOWTIMES_API_KEY=123456679
#     $ internationalshowtimes-get-cinema-id-by-name-and-location "AMC Empire 25" 40.756359 -73.988873
#
# Defaults:
#
#   * `latitude`: $LATITUDE
#   * `longitude`: $LONGITUDE
#
#
# ## Tracking
#
#   * Command: internationalshowtimes-get-cinema-id-by-name-and-location
#   * Version: 3.0.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

name="$1"
latitude="${2:-$LATITUDE}"
longitude="${3:-$LONGITUDE}"

curl -sSLG "http://api.internationalshowtimes.com/v4/cinemas" \
  -H "X-Api-Key: $INTERNATIONALSHOWTIMES_API_KEY" \
  --data-urlencode "location=$latitude,$longitude" |
  jq -r ".cinemas[] | select(.name==\"$name\") | .id" |
  head -1
