#!/bin/sh

## 
# International Showtimes API script to get movies by title
#
# Syntax:
#
#     internationalshowtimes-get-movies-by-title <title>
#
# Example:
#
#     $ export INTERNATIONALSHOWTIMES_API_KEY=123456679
#     $ internationalshowtimes-get-movies-by-title "spider-man"
#
#
# ## Tracking
#
#   * Command: internationalshowtimes-get-movies-by-title
#   * Version: 3.0.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

title="$1"

curl -sSLG "http://api.internationalshowtimes.com/v4/movies" \
  -H "X-Api-Key: $INTERNATIONALSHOWTIMES_API_KEY" \
  --data-urlencode "search_field=title" \
  --data-urlencode "search_query=$title"
