#!/bin/sh

## 
# International Showtimes API script to get cinemas by location
#
# Syntax:
#
#     internationalshowtimes-get-cinemas-by-location [latitude longitude]
#
# Example:
#
#     $ internationalshowtimes-get-cinemas-by-location 40.756359 -73.988873
#
# Defaults:
#
#   * `latitude`: $LATITUDE
#   * `longitude`: $LONGITUDE
#
#
# ## Tracking
#
#   * Command: internationalshowtimes-get-cinemas-by-location
#   * Version: 3.0.0
#   * Created: 2017-08-22
#   * Updated: 2017-09-02
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

latitude="${1:-$LATITUDE}"
longitude="${2:-$LONGITUDE}"

curl -sSLG "http://api.internationalshowtimes.com/v4/cinemas" \
  -H "X-Api-Key: $INTERNATIONALSHOWTIMES_API_KEY" \
  --data-urlencode "location=$latitude,$longitude"
